version: '3'
services:
  app1:
    build: ./app1
    ports:
    - "80:80"
  app2:
    build: ./app2
    ports:
    - "81:80"
  nginx:
    build: ./lb 
    ports:
    - "8080:80"
    depends_on:
      - app1
      - app2
